#!/usr/bin/env bash

if
  [[ -s "/Users/jjbiggins/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/environment" ]]
then
  source "/Users/jjbiggins/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/environment"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/jjbiggins/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/environment'" >&2
  exit 1
fi
